### ISSUE TITLE
Some URLs redirect to / and some don't

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/greensoftware.foundation#5]
This is causing problems with Google indexing out website:

E.g. 

https://greensoftware.foundation/projects/ ends in /

but 

https://greensoftware.foundation/articles/meet-elmar-borgmeier-green-software-foundation-organisation-lead-for-syngenio-ag doesn't end in /

So sometimes the pages end in / and sometimes they don't. I think this is causing problems for Google Index.

![image](https://user-images.githubusercontent.com/897523/196261763-aab6b8d1-7437-4884-8cf6-65dae461b13c.png)

**Comment by zanete** [comment]
@jawache can we clarify the urgency of this?

**Comment by osamajandali** [comment]
@jawache 
I made sure that all the links should not end with slash. I also went now and reviewed all the link in https://greensoftware.foundation and found that I never use a link with slash
I think this happens when someone copy the url and paste it somewhere..the browser automatically put a slash on the end
I made a redirect to remove trailing slash .. let's see if this helps

**Comment by jawache** [comment]
Thanks, let's revisit post COP. This was one of the steps to migrating our website from greensoftware.foundation to greensoftware.org. Google was complaining we have 404's
