### ISSUE TITLE
Article meta tag description is incorrect

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/greensoftware.foundation#7]
Article meta tags are showing the default description instead of the description as setup in the CMS

![image](https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/897523/12f86461-d29a-4878-89f2-a07d71252043)

**Comment by zanete** [comment]
FYI @jawache I've moved this to Post SOGS launch as I understand that is higher priority?

**Comment by osamajandali** [comment]
@jawache, this should be a field from DatoCMS for people to add whatever they want. I feel that no one is using it, shall I spend some time to refactor it to re-use the small description for example ?

**Comment by zanete** [comment]
@jawache cc @NAMRATA-WOKE @ursvill as you should be aware of this super cool feature:
- there is functionality to fully customise the meta tags for SEO for each article and it can be accessed by clicking the "configure" button


![Image](https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/35653799/121b4b35-861b-42cc-b05a-129844c32358)

Because some articles already use this to configure the SEO tags, what we will do as part of this issue is implement the following:
- - IF the meta description field in the SEO form is EMPTY, it will display the short description of the Article instead of the GSF default 
Will that work?

**Comment by ursvill** [comment]
@zanete - yes that will work

**Comment by jawache** [comment]
@zanete yeah sounds good to me!

**Comment by zanete** [comment]
CApturing the satus during weekly call:
- will address this this week

**Comment by osamajandali** [comment]
Done!
